[package]
name = "beauty-list"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "bl"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.55", features = ["derive"] }
owo-colors = "4.2.3"
strum = { version = "0.27.2", features = ["derive"] }
strum_macros = "0.27.2"
tabled = "0.20.0"
